prodId = (int)(input("Enter product Id:"))
prodName = input("Enter product Name:")
prodPrice = (float)(input("Enter product Price:"))

print("***************Print format @1*****************")
print("Product Id:",prodId)
print("Product Name:",prodName)
print("Product Price:",prodPrice)
print("***************Print format @2*****************")
print("Product Id:", prodId,"Product Name:", prodName,"Product Price:",prodPrice)
print("***************Print format @3*****************")
print("Product Id:%d  Product Name:%s Product Price:%f"%(prodId,prodName,prodPrice))
print("***************Print format @4*****************")
print("Product Id:{0} Product Name:{1} Product Price:{2}".format(prodId,prodName,prodPrice))
print("***************Print format @5*****************")
print("Product Id:{} Product Name:{} Product Price:{}".format(prodId,prodName,prodPrice))
print("***************Print format @6 Using separator*****************")
print(prodId,prodName,prodPrice, sep=" ")
