print("***************Tuple data********************************")
xt=()
print(xt)
xt= "ramu", "ravi","chetu", "ramu"
print(xt)
xt= "Ramu","10.5","10"
print(xt)
print("*******************Concatenating tuple data***************")
xt1=("ramu","10.5","20.00")
xt2=(10,20,30,40,50)
xt3=("ramu",10,10.5)
xt4=xt1+xt2+xt3
print(xt4)
print("******************* Nested tuples************************")
xt5=(xt1,xt2,xt3,xt4)
print(xt5)
print("*******************tuple with one value************************")
xt5=(10,)
print(xt5)
print(type(xt5))
print("*******************tuple with indexing************************")
t=(10,20,30,40,50)
print(t[0])
print(t[2:4])
print(t[:4])
print(t[4:])
print(t[:])
print("*******************Tuple unpacking ***************************")
t=(10,20.5,"ramu")
a,b,c=t
print(a,b,c)
print(type(a),type(b),type(c))
print("********************Nested tuples*****************************")
t=((10,20), (30,40,50,60), (70,80))
print(t[0])
print(t[1])
print(t[0][0])
a,b,c=t
print(a,b,c)
print("*******************Retrieve data from tuples******************")
t=(10,20,30,40,50,60,70,80,90)
for x in t:
    print(x)
print("*****Example2*****")
for x in t[:4]:
    print(x)
print("*****Example3*****")
for x in t[2:6]:
    print(x)
print("*****Example5*****")
t=tuple(x+2 for x in range(10))
print(t)
print("************************Replication of tuple data*************")
t1=(10,20,30,40,50,60)
t2=(1,2,3,4,5,6,7,8,9)
t3=t1*2
print(t3)
t4=t2+t3
print(t4)
print("************************touple modification example*************")
t1=(1,2,3,4,5,6,7,8)
l1=list(t1)
l1.append(0)
l1.insert(8,9)
l1.insert(9,10)
t2=tuple(l1)
print(t2)
